import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Watch X15 Air",
    brand: "fitbit",
    priceInMrp: "6990",
    discountInPercentage: 64,
    categoryName: "Watches",
    inStock: 12,
    featured: true,
    starRating: 4.6,
    cashOnDelivery: true,
    fastDelivery: true,
    imageSrc:
      "https://www.southwestjournal.com/wp-content/uploads/2019/02/Fitbit_Versa_3QTR_Black_ClockDefault.jpeg",
  },
  {
    _id: uuid(),
    title: "Smart Band M3",
    brand: "Noise",
    priceInMrp: "3999",
    discountInPercentage: 70,
    categoryName: "Bands",
    inStock: 20,
    featured: true,
    starRating: 3.8,
    cashOnDelivery: true,
    fastDelivery: false,
    imageSrc:
      "https://5.imimg.com/data5/TestImages/QC/VB/CC/SELLER-74949445/bulk-fitness-waterproof-m3-smart-band-0-87-oled-sports-smart-bracelet-500x500.jpg",
  },
  {
    _id: uuid(),
    title: "Oculus Quest 2",
    brand: "Oculus",
    priceInMrp: "44499",
    discountInPercentage: 27,
    categoryName: "VR Headsets",
    inStock: 0,
    featured: true,
    starRating: 4.8,
    cashOnDelivery: false,
    fastDelivery: false,
    imageSrc: "https://m.media-amazon.com/images/I/615YaAiA-ML._SX679_.jpg",
  },
  {
    _id: uuid(),
    title: "Nike Adapt BB",
    brand: "Nike",
    priceInMrp: "36990",
    discountInPercentage: 40,
    categoryName: "Smart Shoes",
    inStock: 2,
    featured: true,
    starRating: 4.1,
    cashOnDelivery: false,
    fastDelivery: true,
    imageSrc:
      "https://kicksdailyvn.com/wp-content/uploads/2020/08/IMG_9082.png",
  },
  {
    _id: uuid(),
    title: "Fire-Boltt Ninja",
    brand: "Fire-Boltt",
    priceInMrp: "5999",
    discountInPercentage: 67,
    categoryName: "Watches",
    inStock: 16,
    featured: false,
    starRating: 4.1,
    cashOnDelivery: true,
    fastDelivery: true,
    imageSrc: "https://m.media-amazon.com/images/I/61MLir0drXL._AC_UL320_.jpg",
  },
  {
    _id: uuid(),
    title: "boAt Flash",
    brand: "boAt",
    priceInMrp: "6990",
    discountInPercentage: 64,
    categoryName: "Watches",
    inStock: 6,
    featured: true,
    starRating: 4.4,
    cashOnDelivery: true,
    fastDelivery: true,
    imageSrc: "https://m.media-amazon.com/images/I/61xBnF7kD5L._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "OnePlus Smart Band",
    brand: "OnePlus",
    priceInMrp: "2799",
    discountInPercentage: 39,
    categoryName: "Bands",
    inStock: 18,
    featured: true,
    starRating: 3.9,
    cashOnDelivery: true,
    fastDelivery: true,
    imageSrc: "https://m.media-amazon.com/images/I/61XPTRJZcCL._AC_UL320_.jpg",
  },
];
