export {
  getFeaturedProducts,
  priceAfterDiscount,
  getUniqueValues,
  putCommasInPrice,
  getMaxPriceForFilter,
  getSortedProducts,
  getFilteredProducts,
  getProductById,
  totalItemsInCart,
  getTotalMrpInCart,
  getTotalAmount,
  getTotalDiscountOnMrp,
  getFinalAmountToPay,
  getSearchedProducts,
} from "./helpers";
